[colors]
foreground = "#c8d3f5"
background = "#222436"
cursor_bg = "#c8d3f5"
cursor_border = "#c8d3f5"
cursor_fg = "#222436"
selection_bg = "#2d3f76"
selection_fg = "#c8d3f5"
split = "#82aaff"
compose_cursor = "#ff966c"
scrollbar_thumb = "#2f334d"

ansi = ["#1b1d2b", "#ff757f", "#c3e88d", "#ffc777", "#82aaff", "#c099ff", "#86e1fc", "#828bb8"]
brights = ["#444a73", "#ff8d94", "#c7fb6d", "#ffd8ab", "#9ab8ff", "#caabff", "#b2ebff", "#c8d3f5"]

[colors.tab_bar]
inactive_tab_edge = "#1e2030"
background = "#222436"

[colors.tab_bar.active_tab]
fg_color = "#1e2030"
bg_color = "#82aaff"

[colors.tab_bar.inactive_tab]
fg_color = "#545c7e"
bg_color = "#2f334d"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#82aaff"
bg_color = "#2f334d"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#82aaff"
bg_color = "#222436"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#82aaff"
bg_color = "#222436"

[metadata]
aliases = []
author = "folke"
name = "tokyonight_moon"