attribute = { fg = "#7dcfff" }
comment = { fg = "#565f89", modifiers = ["italic"] }
"comment.block.documentation" = { fg = "#e0af68" }
constant = { fg = "#ff9e64" }
"constant.builtin" = { fg = "#2ac3de" }
"constant.builtin.boolean" = { fg = "#ff9e64" }
"constant.character" = { fg = "#9ece6a" }
"constant.character.escape" = { fg = "#bb9af7" }
"constant.numeric" = { fg = "#ff9e64" }
"constant.numeric.float" = { fg = "#ff9e64" }
"constant.numeric.integer" = { fg = "#ff9e64" }
constructor = { fg = "#2ac3de" }
"diagnostic.error" = { underline = { style = "curl" } }
"diagnostic.hint" = { underline = { style = "curl" } }
"diagnostic.info" = { underline = { style = "curl" } }
"diagnostic.warning" = { underline = { style = "curl" } }
"diff.delta" = { fg = "#6183bb" }
"diff.delta.moved" = { fg = "#7aa2f7" }
"diff.minus" = { fg = "#914c54" }
"diff.plus" = { fg = "#449dab" }
error = { fg = "#db4b4b" }
function = { fg = "#7aa2f7" }
"function.builtin" = { fg = "#2ac3de" }
"function.macro" = { fg = "#7dcfff" }
"function.method" = { fg = "#7aa2f7" }
"function.special" = { fg = "#7dcfff" }
hint = { fg = "#1abc9c" }
info = { fg = "#0db9d7" }
keyword = { fg = "#9d7cd8", modifiers = ["italic"] }
"keyword.control" = { fg = "#bb9af7" }
"keyword.control.conditional" = { fg = "#bb9af7" }
"keyword.control.exception" = { fg = "#bb9af7" }
"keyword.control.repeat" = { fg = "#bb9af7" }
"keyword.control.return" = { fg = "#9d7cd8", modifiers = ["italic"] }
"keyword.directive" = { fg = "#7dcfff" }
"keyword.function" = { fg = "#bb9af7" }
"keyword.operator" = { fg = "#bb9af7" }
label = { fg = "#7aa2f7" }
"markup.bold" = { modifiers = ["bold"] }
"markup.heading" = { fg = "#7aa2f7", modifiers = ["bold"] }
"markup.heading.completion" = { bg = "#1f2335", fg = "#c0caf5" }
"markup.heading.hover" = { bg = "#363d59" }
"markup.italic" = { modifiers = ["italic"] }
"markup.link" = { fg = "#7aa2f7", underline = { style = "line" } }
"markup.link.label" = { fg = "#1abc9c" }
"markup.link.text" = { fg = "#1abc9c" }
"markup.link.url" = { underline = { style = "line" } }
"markup.list" = { fg = "#ff9e64", modifiers = ["bold"] }
"markup.normal.completion" = { fg = "#565f89" }
"markup.normal.hover" = { fg = "#a9b1d6" }
"markup.raw" = { fg = "#1abc9c" }
"markup.raw.block" = { fg = "#1abc9c" }
"markup.raw.inline" = { bg = "#414868", fg = "#7aa2f7" }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
namespace = { fg = "#7dcfff" }
operator = { fg = "#89ddff" }
special = { fg = "#2ac3de" }
string = { fg = "#9ece6a" }
"string.regexp" = { fg = "#b4f9f8" }
"string.special" = { fg = "#2ac3de" }
tag = { fg = "#bb9af7" }
type = { fg = "#2ac3de" }
"type.builtin" = { fg = "#29a4bd" }
"type.enum" = { fg = "#2ac3de" }
"type.enum.variant" = { fg = "#ff9e64" }
"ui.background" = { bg = "bg" }
"ui.cursor" = { bg = "#c0caf5", fg = "#24283b" }
"ui.cursor.match" = { fg = "#ff9e64", modifiers = ["bold"] }
"ui.linenr" = { fg = "#3b4261" }
"ui.linenr.select" = { fg = "#737aa2" }
"ui.menu" = { bg = "#1f2335", fg = "#c0caf5" }
"ui.menu.scroll" = { bg = 2764351, fg = 3883617 }
"ui.menu.selected" = { bg = "#363d59" }
"ui.popup" = { bg = "#1f2335", fg = "#29a4bd" }
"ui.selection" = { bg = "bg_highlight" }
"ui.statusline" = { bg = "#1f2335", fg = "#a9b1d6" }
"ui.statusline.inactive" = { bg = "#1f2335", fg = "#3b4261" }
"ui.statusline.normal" = { bg = "blue", fg = "black" }
"ui.text" = { bg = "#24283b", fg = "#c0caf5" }
"ui.text.focus" = { bg = "#2e3c64" }
"ui.text.inactive" = { fg = "#565f89", modifiers = ["italic"] }
"ui.text.info" = { bg = "#1f2335", fg = "#c0caf5" }
"ui.virtual.inlay-hint" = { bg = "#233745", fg = "#1abc9c" }
"ui.window" = { fg = "#1d202f", modifiers = ["bold"] }
variable = { fg = "#c0caf5" }
"variable.builtin" = { fg = "#f7768e" }
"variable.other.member" = { fg = "#73daca" }
"variable.parameter" = { fg = "#e0af68" }
warning = { fg = "#e0af68" }

[palette]
bg = "#24283b"
bg_dark = "#1f2335"
bg_float = "#1f2335"
bg_highlight = "#292e42"
bg_popup = "#1f2335"
bg_search = "#3d59a1"
bg_sidebar = "#1f2335"
bg_statusline = "#1f2335"
bg_visual = "#2e3c64"
black = "#1d202f"
blue = "#7aa2f7"
blue0 = "#3d59a1"
blue1 = "#2ac3de"
blue2 = "#0db9d7"
blue5 = "#89ddff"
blue6 = "#b4f9f8"
blue7 = "#394b70"
border = "#1d202f"
border_highlight = "#29a4bd"
comment = "#565f89"
cyan = "#7dcfff"
dark3 = "#545c7e"
dark5 = "#737aa2"
"delta.add" = "#316172"
"delta.delete" = "#763842"
"diff.add" = "#283b4d"
"diff.change" = "#272d43"
"diff.delete" = "#3f2d3d"
"diff.text" = "#394b70"
error = "#db4b4b"
fg = "#c0caf5"
fg_dark = "#a9b1d6"
fg_float = "#c0caf5"
fg_gutter = "#3b4261"
fg_sidebar = "#a9b1d6"
"git.add" = "#449dab"
"git.change" = "#6183bb"
"git.delete" = "#914c54"
"git.ignore" = "#545c7e"
"gitSigns.add" = "#266d6a"
"gitSigns.change" = "#536c9e"
"gitSigns.delete" = "#b2555b"
green = "#9ece6a"
green1 = "#73daca"
green2 = "#41a6b5"
hint = "#1abc9c"
info = "#0db9d7"
magenta = "#bb9af7"
magenta2 = "#ff007c"
orange = "#ff9e64"
purple = "#9d7cd8"
red = "#f7768e"
red1 = "#db4b4b"
teal = "#1abc9c"
terminal_black = "#414868"
warning = "#e0af68"
yellow = "#e0af68"