[manager]
# NOTE: can combined with tmTheme (sublime colorshceme file) for preview code highlight
# highlight = "path/to/tmTheme"

cwd = { fg = "#a9b1d6", italic = true }

# Hovered
hovered         = { bg = "#292e42" }
preview_hovered = { bg = "#292e42" }

# Find
find_keyword  = { fg = "#16161e", bg = "#ff9e64", bold = true }
find_position = { fg = "#0db9d7", bg = "#192b38", bold = true }

# Marker
marker_copied   = { fg = "#73daca", bg = "#73daca" }
marker_cut      = { fg = "#f7768e", bg = "#f7768e" }
marker_marked   = { fg = "#bb9af7", bg = "#bb9af7" }
marker_selected = { fg = "#7aa2f7", bg = "#7aa2f7" }

# Tab
tab_active   = { fg = "#c0caf5", bg = "#292e42" }
tab_inactive = { fg = "#3b4261", bg = "#1a1b26" }
tab_width    = 1

# Count
count_copied   = { fg = "#c0caf5", bg = "#41a6b5" }
count_cut      = { fg = "#c0caf5", bg = "#db4b4b" }
count_selected = { fg = "#c0caf5", bg = "#3d59a1" }
# Border
border_symbol = "│"
border_style  = { fg = "#27a1b9" }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#3b4261", bg = "#3b4261" }

# Mode
mode_normal = { fg = "#16161e", bg = "#7aa2f7", bold = true }
mode_select = { fg = "#16161e", bg = "#bb9af7", bold = true }
mode_unset  = { fg = "#16161e", bg = "#9d7cd8", bold = true }

# Progress
progress_label  = { fg = "#a9b1d6", bold = true }
progress_normal = { fg = "#1a1b26" }
progress_error  = { fg = "#f7768e" }

# Permissions
permissions_t = { fg = "#7aa2f7" }
permissions_r = { fg = "#e0af68" }
permissions_w = { fg = "#f7768e" }
permissions_x = { fg = "#9ece6a" }
permissions_s = { fg = "#414868" }

[select]
border   = { fg = "#27a1b9" }
active   = { fg = "#c0caf5",  bg = "#283457" }
inactive = { fg = "#c0caf5" }

# Input
[input]
border   = { fg = "#0db9d7" }
title    = {}
value    = { fg = "#9d7cd8" }
selected = { bg = "#283457" }

# Completion
[completion]
border   = { fg = "#0db9d7" }
active   = { fg = "#c0caf5", bg = "#283457" }
inactive = { fg = "#c0caf5" }

# Tasks
[tasks]
border  = { fg = "#27a1b9" }
title   = {}
hovered = { fg = "#c0caf5", bg="#283457" }

# Which
[which]
cols = 3
mask            = { bg = "#16161e" }
cand            = { fg = "#7dcfff" }
rest            = { fg = "#7aa2f7" }
desc            = { fg = "#bb9af7" }
separator       = "  "
separator_style = { fg = "#565f89" }

# Notify
[notify]
title_info  = { fg = "#0db9d7" }
title_warn  = { fg = "#e0af68" }
title_error = { fg = "#f7768e" }

# Help
[help]
on      = { fg = "#9ece6a" }
run     = { fg = "#bb9af7" }
hovered = { bg = "#283457" }
footer  = { fg = "#c0caf5", bg = "#1a1b26" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#e0af68" },

	# Media
	{ mime = "{audio,video}/*", fg = "#bb9af7" },

	# Archives
	{ mime = "application/*zip", fg = "#f7768e" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#f7768e" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#7dcfff" },

	# Empty files
	# { mime = "inode/x-empty", fg = "#f7768e" },

	# Special files
	{ name = "*", is = "orphan", bg = "#f7768e" },
	{ name = "*", is = "exec"  , fg = "#9ece6a" },

	# Fallback
	{ name = "*/", fg = "#7aa2f7" }
]
    