name: ğŸ¤– Automation
on:
  pull_request:
    branches: [main]
  pull_request_target:
    branches: [main]
  issues:
    types: [opened, edited, milestoned, demilestoned, closed, reopened]
jobs:
  label:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: ğŸ”– Labeler
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  greet:
    if: ${{ github.event_name == 'issues' || github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: ğŸ«‚ Greeter
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '## ğŸ™ Thanks for opening this issue! We will look into it ASAP.'
          pr-message: '## ğŸ™ Thanks for opening this PR! We will look into it ASAP.'
